// types/index.ts

export interface UserData {
    id?: string // Optional because this will be generated by Prisma
    name: string
    experiences: Experience[]
    educations: Education[]
    skills: Skill[]
    projects: Project[]
    achievements: Achievement[]
    certifications: Certification[]
  }
  
  export interface Experience {
    from: string
    to: string
    jobTitle: string
    company: string
    location: string
  }
  
  export interface Education {
    schoolName: string
    from: string
    to: string
    courseWork: string
    honors?: string
  }
  
  export interface Skill {
    name: string
    subDescription: string
  }
  
  export interface Project {
    name: string
    description: string
    duration: string
    descriptions: ProjectDescription[]
  }
  
  export interface ProjectDescription {
    points: string
  }
  
  export interface Achievement {
    name: string
    description: string
    link?: string
  }
  
  export interface Certification {
    name: string
    description: string
    link?: string
  }
  